In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
# Q1. Is there any difference in the data type of variables list_ and array_list?
print(f"Data type of list_: {type(list_)}")  # Type of list_
print(f"Data type of array_list: {type(array_list)}")  # Type of array_list

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [5]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list?
# Data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [6]:
# Q3. Considering the following changes in the variable array_list:
array_list = np.array(object=list_, dtype=int)

# Data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Data types of elements in array_list
print("Data types of elements in array_list after dtype=int:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list after dtype=int:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [9]:
# Q4. Characteristics of variable num_array:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Shape of num_array
print(f"Shape of num_array: {num_array.shape}")

# Size of num_array
print(f"Size of num_array: {num_array.size}")


Shape of num_array: (2, 3)
Size of num_array: 6


In [10]:
# Q5. Create a 3×3 matrix containing zeros only:
# Creating a 3x3 matrix of zeros
zeros_matrix = np.zeros((3, 3))
print("3x3 Matrix containing zeros:")
print(zeros_matrix)

3x3 Matrix containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Q6. Create an identity matrix of shape (5,5):
# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
